spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-circular-references: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.mongodb.driver: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    com.sathwikhbhat: INFO